name: 'aws_dbt_snowflake_project'
version: '1.0.0'

profile: 'aws_dbt_snowflake_project'

model-paths: ["models/demo"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"


models:
  aws_dbt_snowflake_project:
      +materialized: table
      bronze:
        +schema: bronze
      silver:
        +schema: silver
      gold:
        +schema: gold

        ephemeral:
          +materialized: ephemeral


        